services:
    #   PHP Server
    inventory_manager:
        build:
            context: . # path of Dockerfile
            dockerfile: docker/Dockerfile.prod
        image: inventory_manager
        container_name: inventory_manager
        ports:
            -   "10101:80"
        restart: unless-stopped # automatically restarts the server if stops
        working_dir: /var/www # [/var/www] is the standard though you can use any name
        volumes:
            - ./:/var/www
        networks:
            - prometheus-network


#   Docker Networks
networks:
    prometheus-network:
        external: true


