services:
    #   PHP Server
    inventory_manager:
        build:
            context: . # path of Dockerfile
            dockerfile: docker/Dockerfile.prod
        image: inventory_manager
        container_name: inventory_manager
        ports:
            - "10101:80"
        restart: unless-stopped # automatically restarts the server if stops
        working_dir: /var/www # [/var/www] is the standard though you can use any name
        environment:
            VIRTUAL_HOST: inventory-manager.dev
        volumes:
            - ./:/var/www
        networks:
            - prometheus-network
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M
                reservations:
                    cpus: '0.1'
                    memory: 128M


#   Docker Networks
networks:
    prometheus-network:
        external: true


